"""Interactive setup: connect Rube apps, write config.json, create the weekly recipe."""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
CONFIG_PATH = SKILL_ROOT / "config.json"
EXAMPLE_PATH = SKILL_ROOT / "config.example.json"


def _input(prompt: str, default: str | None = None) -> str:
    if default is not None:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    value = input(prompt).strip()
    if not value and default is not None:
        return default
    return value


def _check_rube_env() -> None:
    if not os.environ.get("COMPOSIO_API_KEY"):
        print("\n❌ COMPOSIO_API_KEY is not set.")
        print("   1. Sign up at https://rube.app")
        print("   2. Get your API key.")
        print("   3. Add to your shell: export COMPOSIO_API_KEY=...")
        sys.exit(2)


def _ensure_connections(rube) -> None:
    print("\n› מחבר את Google Sheets ו-Gmail דרך Rube...")
    try:
        rube.execute_tool("RUBE_MANAGE_CONNECTIONS", {"action": "ensure", "apps": ["googlesheets", "gmail"]})
        print("✓ חיבורים מוכנים.")
    except Exception as exc:  # noqa: BLE001
        print(f"⚠️ לא הצלחתי להבטיח חיבורים: {exc}")
        print("   המשך והשלם את החיבורים ידנית בלוח הבקרה של Rube.")


def _load_template() -> dict:
    with open(EXAMPLE_PATH, encoding="utf-8") as f:
        return json.load(f)


def _prompt_config(template: dict) -> dict:
    cfg = json.loads(json.dumps(template))  # deep copy

    cfg["sheet"]["spreadsheet_id"] = _input("מזהה Google Sheet (Spreadsheet ID)")
    tabs_str = _input("שמות טאבים מופרדים בפסיק (אופיר, אביב, ...)")
    cfg["sheet"]["employee_tabs"] = [t.strip() for t in tabs_str.split(",") if t.strip()]

    cfg["email"]["recipient"] = _input("כתובת מייל ליעד")
    cc_str = _input("עותקים (CC) — מייל אחד או יותר מופרדים בפסיק (Enter לדלג)", default="")
    cfg["email"]["cc"] = [c.strip() for c in cc_str.split(",") if c.strip()] if cc_str else []

    cron = _input("Cron (default ראשון 08:00)", default=cfg["schedule"]["cron"])
    cfg["schedule"]["cron"] = cron
    return cfg


def _write_config(cfg: dict) -> None:
    with open(CONFIG_PATH, "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)
    print(f"✓ נכתב {CONFIG_PATH}")


def _register_recipe(rube, cfg: dict) -> None:
    print("\n› יוצר Composio recipe + cron schedule...")
    recipe_name = "weekly-hours-report"
    bash_step = (
        "cd ~/.claude/skills/weekly-hours-report && "
        "python scripts/generate_report.py"
    )
    try:
        rube.execute_tool(
            "RUBE_CREATE_UPDATE_RECIPE",
            {
                "name": recipe_name,
                "description": "Weekly Hebrew employee-hours report — generated by the weekly-hours-report skill.",
                "steps": [
                    {"tool": "RUBE_REMOTE_BASH_TOOL", "params": {"command": bash_step}},
                ],
            },
        )
        rube.execute_tool(
            "RUBE_MANAGE_RECIPE_SCHEDULE",
            {
                "recipe": recipe_name,
                "action": "schedule",
                "cron": cfg["schedule"]["cron"],
                "timezone": cfg["schedule"]["timezone"],
            },
        )
        print("✓ Recipe + cron נרשמו.")
    except Exception as exc:  # noqa: BLE001
        print(f"⚠️ Recipe creation failed: {exc}")
        print("   ניתן ליצור recipe ידנית מ-Rube dashboard עם הפקודה:")
        print(f"   {bash_step}")


def _offer_test_send() -> None:
    ans = _input("\nלשלוח דוח test עכשיו? (y/n)", default="n")
    if ans.lower().startswith("y"):
        import subprocess
        subprocess.run([sys.executable, "scripts/generate_report.py"], cwd=str(SKILL_ROOT), check=False)


def main() -> int:
    print("=" * 60)
    print("Weekly Hours Report — Setup")
    print("=" * 60)
    _check_rube_env()

    from scripts.generate_report import get_rube_client
    rube = get_rube_client()
    _ensure_connections(rube)

    template = _load_template()
    cfg = _prompt_config(template)
    _write_config(cfg)
    _register_recipe(rube, cfg)
    _offer_test_send()

    print("\n✓ הסיום! הדוח השבועי הבא יישלח בהתאם ל-cron שהגדרת.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
